# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '51ALP_IOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 51ALP_IOS
  pod 'Material', '~> 2.0'
  pod 'SnapKit', '~> 4.2.0'
  pod "CenteredCollectionView"
  pod 'DynamicColor', '~> 4.0.3'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'Eureka'
  pod 'SCLAlertView'
  pod 'PopupDialog', '~> 0.9'
  pod 'Cosmos'
  pod 'BadgeSwift', '~> 7.0'
  pod 'BMPlayer', '~> 1.2.0'
  pod ‘StepIndicator’, '~> 1.0.6’
  pod 'Alamofire', '~> 4.8.0'
  pod "PromiseKit", "~> 6.0"
  pod 'SwiftValidators'
  pod 'SwiftMessages'
  pod 'RealmSwift'
  pod 'JGProgressHUD'
  pod 'HGPlaceholders'
  pod 'FaceAware'
  pod 'SDWebImage', '~> 4.0'
 
end
